Repository Blinue/Magpie, pull requests merged in 2023-11, with the labels that each got.

#747 feat: 适配 Win11 23H2
  src/Magpie/app.manifest
Labels: enhancement

#749 修正贴靠布局弹窗位置
  src/Magpie/MainWindow.cpp
  src/Magpie/MainWindow.h
Labels: bug, area: UI

#750 使用正式版 WinUI
  Magpie.sln
  publish.py
  src/Common.Post.props
  src/HybridCRT.props
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/ProfilePage.xaml
  src/Magpie.App/packages.config
  src/Magpie/Magpie.vcxproj
  src/Magpie/packages.config
  src/WinUI.props
  src/extract_winui_runtime.py
  src/fix_resfiles.py
Labels: area: UI, area: build

#758 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-ja.resw
  src/Magpie.App/Resources.language-zh-Hant.resw
Labels: area: localization

#754 惰性加载某些控件以提高页面加载速度
  src/Magpie.App/AboutPage.cpp
  src/Magpie.App/AboutPage.idl
  src/Magpie.App/AboutPage.xaml
  src/Magpie.App/AboutViewModel.cpp
  src/Magpie.App/AboutViewModel.h
  src/Magpie.App/AboutViewModel.idl
  src/Magpie.App/App.cpp
  src/Magpie.App/App.h
  src/Magpie.App/App.idl
  src/Magpie.App/EffectParametersViewModel.h
  src/Magpie.App/EffectParametersViewModel.idl
  src/Magpie.App/HomePage.idl
  src/Magpie.App/HomePage.xaml
  src/Magpie.App/HomeViewModel.cpp
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/Magpie.App.vcxproj.filters
  src/Magpie.App/PageFrame.cpp
  src/Magpie.App/ProfilePage.idl
  src/Magpie.App/ProfilePage.xaml
  src/Magpie.App/ProfileViewModel.cpp
  src/Magpie.App/ProfileViewModel.h
  src/Magpie.App/RootPage.cpp
  src/Magpie.App/RootPage.h
  src/Magpie.App/RootPage.idl
  src/Magpie.App/RootPage.xaml
  src/Magpie.App/ScalingConfigurationPage.idl
  src/Magpie.App/ScalingConfigurationPage.xaml
  src/Magpie.App/ScalingModeItem.cpp
  src/Magpie.App/SettingsPage.idl
  src/Magpie.App/SettingsPage.xaml
  src/Magpie.App/TitlebarControl.cpp
  src/Magpie.App/WrapPanel.cpp
  src/Magpie/MainWindow.cpp
  src/Magpie/MainWindow.h
  src/Magpie/XamlApp.cpp
  src/Magpie/XamlWindow.h
  src/Magpie/app.manifest
Labels: area: performance, area: UI

#759 几处 UI 优化
  src/Magpie.App/CaptionButtonsControl.cpp
  src/Magpie.App/HomePage.cpp
  src/Magpie.App/HomePage.h
  src/Magpie.App/HomePage.xaml
  src/Magpie.App/PageFrame.cpp
  src/Magpie.App/RootPage.cpp
  src/Magpie.App/RootPage.h
  src/Magpie.App/ScalingModeItem.cpp
  src/Magpie/XamlWindow.h
  src/Shared/XamlUtils.cpp
  src/Shared/XamlUtils.h
Labels: bug, area: UI

#760 修复新配置候选窗口有时会包含不可见的窗口的问题
  src/Magpie.App/NewProfileViewModel.cpp
Labels: bug

#761 防止窗口启动时不在可见区域
  src/Magpie/MainWindow.cpp
  src/Magpie/MainWindow.h
  src/Magpie/XamlApp.cpp
  src/Magpie/XamlApp.h
Labels: bug

#762 优化主窗口位置
  src/Magpie.App/App.cpp
  src/Magpie.App/App.idl
  src/Magpie.App/AppSettings.cpp
  src/Magpie.App/AppSettings.h
  src/Magpie/MainWindow.cpp
  src/Magpie/MainWindow.h
  src/Magpie/XamlApp.cpp
  src/Magpie/XamlApp.h
Labels: enhancement, area: UI

#766 优化发布脚本
  .github/workflows/release.yml
  publish.py
Labels: github_actions
