Repository Blinue/Magpie, pull requests merged in 2023-12, with the labels that each got.

#770 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-zh-Hant.resw
Labels: area: localization

#777 优化 SettingsExpander 的性能
  src/Magpie.App/ScalingConfigurationPage.xaml
  src/Magpie.App/SettingsCard.cpp
  src/Magpie.App/SettingsExpander.cpp
  src/Magpie.App/SettingsExpander.h
  src/Magpie.App/SettingsExpander.idl
  src/Magpie.App/SettingsExpander.xaml
  src/Magpie.App/ShortcutDialog.xaml
Labels: area: performance, area: UI

#778 修复空缩放模式导致的崩溃
  src/Magpie.App/SettingsCard.cpp
Labels: bug, area: UI

#779 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-fr.resw
Labels: area: localization

#781 重构 SettingsGroup
  src/Magpie.App/App.xaml
  src/Magpie.App/Button.xaml
  src/Magpie.App/HomePage.xaml
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/Magpie.App.vcxproj.filters
  src/Magpie.App/ProfilePage.xaml
  src/Magpie.App/ScalingConfigurationPage.xaml
  src/Magpie.App/SettingsCard.cpp
  src/Magpie.App/SettingsGroup.cpp
  src/Magpie.App/SettingsGroup.h
  src/Magpie.App/SettingsGroup.idl
  src/Magpie.App/SettingsGroup.xaml
  src/Magpie.App/SettingsPage.xaml
  src/Magpie.App/ShortcutControl.xaml
Labels: area: UI

#784 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-fr.resw
Labels: area: localization

#783 添加 SimpleStackPanel：没有间距错误的轻量级 StackPanel
  src/Magpie.App/AboutPage.xaml
  src/Magpie.App/App.idl
  src/Magpie.App/App.xaml
  src/Magpie.App/CaptionButtonsControl.cpp
  src/Magpie.App/CaptionButtonsControl.h
  src/Magpie.App/CaptionButtonsControl.idl
  src/Magpie.App/CaptionButtonsControl.xaml
  src/Magpie.App/HomePage.xaml
  src/Magpie.App/KeyVisualState.idl
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/Magpie.App.vcxproj.filters
  src/Magpie.App/PageFrame.idl
  src/Magpie.App/PageFrame.xaml
  src/Magpie.App/ProfilePage.xaml
  src/Magpie.App/RootPage.xaml
  src/Magpie.App/ScalingConfigurationPage.xaml
  src/Magpie.App/SettingsCard.xaml
  src/Magpie.App/SettingsGroup.xaml
  src/Magpie.App/SettingsPage.xaml
  src/Magpie.App/ShortcutControl.xaml
  src/Magpie.App/ShortcutDialog.xaml
  src/Magpie.App/SimpleStackPanel.cpp
  src/Magpie.App/SimpleStackPanel.h
  src/Magpie.App/SimpleStackPanel.idl
  src/Magpie.App/TitlebarControl.xaml
  src/Magpie.App/WrapPanel.cpp
  src/Magpie.App/WrapPanel.h
  src/Magpie.App/WrapPanel.idl
Labels: enhancement, area: UI

#787 动态决定是否检测重复帧
  src/Magpie.App/AboutViewModel.cpp
  src/Magpie.App/AboutViewModel.h
  src/Magpie.App/AppSettings.cpp
  src/Magpie.App/AppSettings.h
  src/Magpie.App/Profile.h
  src/Magpie.App/ProfilePage.xaml
  src/Magpie.App/ProfileViewModel.cpp
  src/Magpie.App/ProfileViewModel.h
  src/Magpie.App/ProfileViewModel.idl
  src/Magpie.App/Resources.language-en-US.resw
  src/Magpie.App/Resources.language-es.resw
  src/Magpie.App/Resources.language-fr.resw
  src/Magpie.App/Resources.language-it.resw
  src/Magpie.App/Resources.language-ja.resw
  src/Magpie.App/Resources.language-ko.resw
  src/Magpie.App/Resources.language-pt-BR.resw
  src/Magpie.App/Resources.language-ru.resw
  src/Magpie.App/Resources.language-tr.resw
  src/Magpie.App/Resources.language-uk.resw
  src/Magpie.App/Resources.language-vi.resw
  src/Magpie.App/Resources.language-zh-Hans.resw
  src/Magpie.App/Resources.language-zh-Hant.resw
  src/Magpie.App/ScalingService.cpp
  src/Magpie.App/ScalingService.h
  src/Magpie.App/SettingsPage.xaml
  src/Magpie.App/SettingsViewModel.cpp
  src/Magpie.App/SettingsViewModel.h
  src/Magpie.App/SettingsViewModel.idl
  src/Magpie.Core/FrameSourceBase.cpp
  src/Magpie.Core/FrameSourceBase.h
  src/Magpie.Core/OverlayDrawer.cpp
  src/Magpie.Core/Renderer.cpp
  src/Magpie.Core/Renderer.h
  src/Magpie.Core/ScalingOptions.h
  src/Shared/Win32Utils.cpp
  src/Shared/Win32Utils.h
Labels: area: performance, area: capture

#790 优化叠加层渲染性能
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/conanfile.txt
  src/Magpie.App/packages.config
  src/Magpie.Core/BackendDescriptorStore.cpp
  src/Magpie.Core/BackendDescriptorStore.h
  src/Magpie.Core/CursorDrawer.cpp
  src/Magpie.Core/CursorDrawer.h
  src/Magpie.Core/DeviceResources.cpp
  src/Magpie.Core/DeviceResources.h
  src/Magpie.Core/DirectXHelper.cpp
  src/Magpie.Core/EffectDrawer.cpp
  src/Magpie.Core/EffectDrawer.h
  src/Magpie.Core/FrameSourceBase.cpp
  src/Magpie.Core/FrameSourceBase.h
  src/Magpie.Core/ImGuiBackend.cpp
  src/Magpie.Core/ImGuiBackend.h
  src/Magpie.Core/ImGuiImpl.cpp
  src/Magpie.Core/ImGuiImpl.h
  src/Magpie.Core/Magpie.Core.vcxproj
  src/Magpie.Core/Magpie.Core.vcxproj.filters
  src/Magpie.Core/OverlayDrawer.cpp
  src/Magpie.Core/OverlayDrawer.h
  src/Magpie.Core/Renderer.cpp
  src/Magpie.Core/Renderer.h
  src/Magpie.Core/ScalingRuntime.cpp
  src/Magpie.Core/ScalingRuntime.h
  src/Magpie.Core/TextureLoader.cpp
  src/Magpie.Core/shaders/DuplicateFrameCS.hlsl
  src/Magpie.Core/shaders/ImGuiImplPS.hlsl
  src/Magpie.Core/shaders/ImGuiImplVS.hlsl
  src/Magpie/Magpie.vcxproj
  src/Magpie/packages.config
Labels: area: performance, area: UI

#795 支持 ARM64 架构
  .github/workflows/build.yml
  .github/workflows/release.yml
  ci/release.py
  publish.py
  src/Magpie.App/App.cpp
  src/Magpie.App/App.h
  src/Magpie.App/Magpie.App.def
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/Magpie.App.vcxproj.filters
  src/Magpie.App/UpdateService.cpp
  src/Magpie.App/app.base.h
  src/Magpie.Core/Magpie.Core.vcxproj
  src/Magpie/Magpie.vcxproj
  src/Magpie/XamlIslands.targets
Labels: enhancement
