Repository Blinue/Magpie, pull requests merged in 2024-01, with the labels that each got.

#810 支持 XAML 热重载
  Magpie.sln
  publish.py
  src/Common.Post.props
  src/HybridCRT.props
  src/Magpie.App/AboutPage.cpp
  src/Magpie.App/AboutViewModel.cpp
  src/Magpie.App/App.xaml
  src/Magpie.App/AppSettings.cpp
  src/Magpie.App/HomeViewModel.cpp
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/Magpie.App.vcxproj.filters
  src/Magpie.App/NewProfileViewModel.cpp
  src/Magpie.App/Package.appxmanifest
  src/Magpie.App/ProfileViewModel.cpp
  src/Magpie.App/ScalingConfigurationViewModel.cpp
  src/Magpie.App/ScalingModeEffectItem.cpp
  src/Magpie.App/ScalingModeItem.cpp
  src/Magpie.App/SettingsPage.cpp
  src/Magpie.App/SettingsViewModel.cpp
  src/Magpie.App/ShortcutControl.cpp
  src/Magpie.App/ShortcutDialog.cpp
  src/Magpie.App/conanfile.txt
  src/Magpie.App/dummy.exe
  src/Magpie.App/make_resources_pri.py
  src/Magpie.Core/OverlayDrawer.cpp
  src/Magpie.Core/OverlayDrawer.h
  src/Magpie/Magpie.vcxproj
  src/Magpie/Magpie.vcxproj.filters
  src/Magpie/TrayIconService.cpp
  src/Magpie/XamlIslands.targets
  src/Magpie/app.manifest
  src/Magpie/conanfile.txt
  src/Shared/CommonSharedConstants.h
  src/WinUI.props
  src/_ConanDeps/build_conan_deps.py
  src/extract_winui_runtime.py
  src/fix_resfiles.py
Labels: area: build

#812 修复缩放窗口不能跨越多个屏幕的错误
  src/Magpie.Core/MagApp.cpp
Labels: bug

#814 Fix generation of effect source files in subdirectories
  src/Magpie.Core/EffectCompiler.cpp
Labels: bug

#824 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-de.resw
Labels: area: localization
