Repository Blinue/Magpie, pull requests merged in 2024-12, with the labels that each got.

#1022 全局消息弹窗
  src/Magpie.App/AboutPage.cpp
  src/Magpie.App/AboutViewModel.cpp
  src/Magpie.App/App.cpp
  src/Magpie.App/App.xaml
  src/Magpie.App/HomePage.cpp
  src/Magpie.App/IconHelper.cpp
  src/Magpie.App/IconHelper.h
  src/Magpie.App/Magpie.App.vcxproj
  src/Magpie.App/Magpie.App.vcxproj.filters
  src/Magpie.App/Resources.language-en-US.resw
  src/Magpie.App/Resources.language-zh-Hans.resw
  src/Magpie.App/RootPage.cpp
  src/Magpie.App/RootPage.h
  src/Magpie.App/RootPage.idl
  src/Magpie.App/RootPage.xaml
  src/Magpie.App/ScalingService.cpp
  src/Magpie.App/ScalingService.h
  src/Magpie.App/ShortcutService.cpp
  src/Magpie.App/TitlebarControl.cpp
  src/Magpie.App/ToastPage.cpp
  src/Magpie.App/ToastPage.h
  src/Magpie.App/ToastPage.idl
  src/Magpie.App/ToastPage.xaml
  src/Magpie.App/ToastService.cpp
  src/Magpie.App/ToastService.h
  src/Magpie.Core/CursorManager.cpp
  src/Magpie.Core/CursorManager.h
  src/Magpie.Core/DwmSharedSurfaceFrameSource.cpp
  src/Magpie.Core/FrameSourceBase.cpp
  src/Magpie.Core/GDIFrameSource.cpp
  src/Magpie.Core/Renderer.cpp
  src/Magpie.Core/Renderer.h
  src/Magpie.Core/ScalingRuntime.cpp
  src/Magpie.Core/ScalingRuntime.h
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
  src/Magpie.Core/StepTimer.cpp
  src/Magpie/XamlWindow.h
  src/Shared/CommonSharedConstants.h
  src/Shared/ScalingError.h
  src/Shared/Shared.vcxitems
  src/Shared/Win32Utils.h
  src/Shared/XamlUtils.h
Labels: enhancement

#1029 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-de.resw
  src/Magpie.App/Resources.language-ja.resw
  src/Magpie.App/Resources.language-ru.resw
Labels: area: localization

#1031 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-ja.resw
Labels: area: localization

#1034 优化标题栏功能
  src/Magpie/MainWindow.cpp
  src/Magpie/XamlWindow.h
Labels: enhancement, area: UI

#1036 Translations update from Hosted Weblate
  src/Magpie/Resources.language-de.resw
  src/Magpie/Resources.language-en-US.resw
  src/Magpie/Resources.language-es.resw
  src/Magpie/Resources.language-fr.resw
  src/Magpie/Resources.language-hu.resw
  src/Magpie/Resources.language-it.resw
  src/Magpie/Resources.language-ja.resw
  src/Magpie/Resources.language-ko.resw
  src/Magpie/Resources.language-pl.resw
  src/Magpie/Resources.language-pt-BR.resw
  src/Magpie/Resources.language-ru.resw
  src/Magpie/Resources.language-tr.resw
  src/Magpie/Resources.language-uk.resw
  src/Magpie/Resources.language-vi.resw
  src/Magpie/Resources.language-zh-Hans.resw
  src/Magpie/Resources.language-zh-Hant.resw
Labels: area: localization

#1039 Translations update from Hosted Weblate
  src/Magpie/Resources.language-tr.resw
Labels: area: localization

#1040 刚显示窗口时跳过动画
  src/Magpie/CandidateWindowItem.h
  src/Magpie/ContentDialogHelper.h
  src/Magpie/HomePage.cpp
  src/Magpie/KeyVisual.h
  src/Magpie/MainWindow.cpp
  src/Magpie/PageFrame.cpp
  src/Magpie/PageFrame.h
  src/Magpie/ProfilePage.cpp
  src/Magpie/ProfilePage.h
  src/Magpie/ProfileViewModel.h
  src/Magpie/RootPage.cpp
  src/Magpie/ScalingModesPage.cpp
  src/Magpie/ScalingModesPage.h
  src/Magpie/SettingsCard.h
  src/Magpie/SettingsExpander.Resource.xaml
  src/Magpie/SettingsExpander.cpp
  src/Magpie/SettingsExpander.h
  src/Magpie/ShortcutControl.h
  src/Magpie/SimpleStackPanel.cpp
  src/Magpie/SimpleStackPanel.h
  src/Magpie/TextBlockHelper.h
  src/Magpie/TitlebarControl.cpp
  src/Magpie/WrapPanel.cpp
  src/Magpie/WrapPanel.h
  src/Magpie/XamlHelper.cpp
  src/Magpie/XamlHelper.h
  src/Magpie/XamlWindow.h
  src/Magpie/pch.h
Labels: area: UI

#1042 通知区域图标菜单支持定时缩放
  src/Magpie/HomeViewModel.cpp
  src/Magpie/NotifyIconService.cpp
Labels: enhancement
