Repository Blinue/Magpie, pull requests merged in 2024-06, with the labels that each got.

#938 修复忘记释放某些 mutex
  src/Magpie.Core/ExclModeHelper.cpp
  src/Magpie.Core/ScalingWindow.cpp
  src/Updater/main.cpp
Labels: bug

#944 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-pl.resw
Labels: area: localization

#947 优化光标区域裁剪
  src/Magpie.Core/CursorManager.cpp
  src/Magpie.Core/CursorManager.h
Labels: bug, area: compatibility

#948 fix: 缩放窗口销毁前清理属性，以及更新文档说明清理窗口属性
  docs/Interact with Magpie programally.md
  docs/以编程方式与 Magpie 交互.md
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
Labels: bug

#956 游戏图标支持彩色掩码图标
  src/Magpie.App/IconHelper.cpp
Labels: area: UI

#960 支持长路径
  src/Magpie/app.manifest
  src/TouchHelper/app.manifest
  src/Updater/app.manifest
Labels: enhancement
