Repository Blinue/Magpie, pull requests merged in 2024-04, with the labels that each got.

#871 多个性能优化
  src/Magpie.Core/CursorManager.cpp
  src/Magpie.Core/DesktopDuplicationFrameSource.cpp
  src/Magpie.Core/DesktopDuplicationFrameSource.h
  src/Magpie.Core/DwmSharedSurfaceFrameSource.cpp
  src/Magpie.Core/DwmSharedSurfaceFrameSource.h
  src/Magpie.Core/FrameSourceBase.cpp
  src/Magpie.Core/FrameSourceBase.h
  src/Magpie.Core/GDIFrameSource.h
  src/Magpie.Core/GraphicsCaptureFrameSource.cpp
  src/Magpie.Core/GraphicsCaptureFrameSource.h
  src/Magpie.Core/Renderer.cpp
  src/Magpie.Core/Renderer.h
  src/Magpie.Core/StepTimer.cpp
  src/Magpie.Core/StepTimer.h
Labels: area: performance

#873 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-ja.resw
Labels: area: localization

#877 修复对全屏窗口的支持
  src/Magpie.Core/FrameSourceBase.cpp
  src/Shared/Win32Utils.cpp
Labels: bug

#882 缩放配置页面不再展示添加/删除动画
  src/Magpie.App/ScalingConfigurationPage.xaml
  src/Magpie.App/ScalingConfigurationViewModel.cpp
  src/Magpie.App/ScalingConfigurationViewModel.h
  src/Magpie.App/ScalingConfigurationViewModel.idl
  src/Magpie.App/SettingsExpander.Resource.xaml
Labels: area: UI

#885 修复 SimpleStackPanel 的子项绑定有时不起作用的问题
  src/Magpie.App/ScalingConfigurationPage.xaml
  src/Magpie.App/SimpleStackPanel.cpp
Labels: bug, area: UI

#887 修复缩放配置页面的设置项错误折叠的问题
  src/Magpie.App/ScalingConfigurationPage.xaml
Labels: bug, area: UI

#891 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-tr.resw
Labels: area: localization

#895 添加和其他程序交互的机制
  README.md
  README_ZH.md
  docs/Interact with Magpie programally.md
  docs/以编程方式与 Magpie 交互.md
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
  src/Magpie/MainWindow.cpp
  src/Magpie/XamlApp.cpp
  src/Magpie/XamlWindow.h
  src/Shared/CommonSharedConstants.h
  src/Shared/Utils.h
Labels: enhancement
