Repository Blinue/Magpie, pull requests merged in 2024-03, with the labels that each got.

#834 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-de.resw
Labels: area: localization

#839 修复找不到可用显卡时回落到 WARP 失败的问题
  src/Magpie.Core/DeviceResources.cpp
Labels: bug

#840 防止 3D 游戏模式下打开叠加层可能导致的崩溃
  src/Magpie.Core/OverlayDrawer.cpp
Labels: bug

#843 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-ja.resw
Labels: area: localization

#845 Translations update from Hosted Weblate
  src/Magpie.App/Resources.language-de.resw
Labels: area: localization

#821 在叠加层中显示效果处理时间
  src/Magpie.App/conanfile.txt
  src/Magpie.Core/EffectDrawer.cpp
  src/Magpie.Core/EffectDrawer.h
  src/Magpie.Core/EffectsProfiler.cpp
  src/Magpie.Core/EffectsProfiler.h
  src/Magpie.Core/ImGuiImpl.cpp
  src/Magpie.Core/Magpie.Core.vcxproj
  src/Magpie.Core/Magpie.Core.vcxproj.filters
  src/Magpie.Core/OverlayDrawer.cpp
  src/Magpie.Core/OverlayDrawer.h
  src/Magpie.Core/Renderer.cpp
  src/Magpie.Core/Renderer.h
  src/Magpie.Core/ScalingWindow.cpp
Labels: enhancement

#848 Add CuNNy-NVL upscaler
  src/Effects/CuNNy/CuNNy-16x16C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-16x16C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-2x4C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-2x4C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-3x4C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-3x4C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-4x16C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-4x16C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-4x4C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-4x4C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-4x8C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-4x8C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-6x8C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-6x8C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-8x16C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-8x16C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-8x4C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-8x4C-NVL.hlsl
  src/Effects/CuNNy/CuNNy-8x8C-NVL-DN.hlsl
  src/Effects/CuNNy/CuNNy-8x8C-NVL.hlsl
  src/Effects/Effects.vcxproj
  src/Effects/Effects.vcxproj.filters
Labels: area: effect

#855 优化双线性插值下单色光标和彩色掩码光标的渲染效果
  src/Magpie.Core/CursorDrawer.cpp
  src/Magpie.Core/shaders/MaskedCursorPS.hlsl
  src/Magpie.Core/shaders/MonochromeCursorPS.hlsl
Labels: enhancement

#862 简化 ScalingRuntime 状态
  src/Magpie.App/ScalingService.cpp
  src/Magpie.App/ScalingService.h
  src/Magpie.Core/ScalingRuntime.cpp
  src/Magpie.Core/ScalingRuntime.h
  src/Magpie.Core/ScalingWindow.cpp
Labels: bug

#864 优化窗口边框的裁剪
  src/Magpie.Core/DesktopDuplicationFrameSource.cpp
  src/Magpie.Core/FrameSourceBase.cpp
  src/Magpie.Core/GraphicsCaptureFrameSource.cpp
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie/XamlWindow.h
  src/Shared/Win32Utils.cpp
  src/Shared/Win32Utils.h
Labels: enhancement

#866 修复光标移动到叠加层或其他窗口时有时会跳跃的问题
  src/Magpie.Core/CursorManager.cpp
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
Labels: bug

#867 禁止缩放完整性级别更高的窗口
  src/Magpie.App/ScalingService.cpp
  src/Magpie.App/ScalingService.h
  src/Shared/Win32Utils.cpp
  src/Shared/Win32Utils.h
Labels: enhancement
