Repository Blinue/Magpie, pull requests merged in 2025-05, with the labels that each got.

#1139 避免短时间内多次启动 TouchHelper 时弹出消息
  src/Magpie.Core/include/CommonSharedConstants.h
  src/Magpie/TouchHelper.cpp
  src/TouchHelper/main.cpp
Labels: bug

#1140 Suggest Hardware-accelerated GPU scheduling
  docs/Performance optimization.md
  docs/性能优化建议.md
Labels: area: performance, area: docs

#1141 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ru.resw
Labels: area: localization

#1142 修复消息弹出动画错误
  src/Magpie.Core/Magpie.Core.vcxproj.filters
  src/Magpie/ToastPage.cpp
  src/Magpie/XamlHelper.cpp
  src/Magpie/XamlHelper.h
  src/TouchHelper/TouchHelper.vcxproj.filters
  src/Updater/Updater.vcxproj.filters
Labels: bug, area: UI

#1146 提高 GPU 优先级
  src/Magpie.Core/Renderer.cpp
Labels: area: performance

#1150 默认快捷键的 Win 改为 Alt 以避免和系统快捷键冲突
  src/Magpie/AppSettings.cpp
Labels: bug, area: compatibility

#1151 不在任何屏幕上的窗口不检查自动缩放
  src/Magpie/ScalingService.cpp
Labels: bug, area: compatibility

#1152 修复特定情况下打开文本框右键菜单会崩溃的问题
  src/Magpie/AboutPage.h
  src/Magpie/App.h
  src/Magpie/App.idl
  src/Magpie/BlueInfoBarStyle.h
  src/Magpie/BoolNegationConverter.h
  src/Magpie/BoolToNegativeVisibilityConverter.h
  src/Magpie/CaptionButtonsControl.h
  src/Magpie/ComboBoxHelper.h
  src/Magpie/ControlHelper.cpp
  src/Magpie/ControlHelper.h
  src/Magpie/ControlSizeTrigger.h
  src/Magpie/HomePage.cpp
  src/Magpie/HomePage.h
  src/Magpie/HomeViewModel.h
  src/Magpie/IsEqualStateTrigger.h
  src/Magpie/IsNullStateTrigger.h
  src/Magpie/KeyVisual.h
  src/Magpie/Magpie.vcxproj
  src/Magpie/Magpie.vcxproj.filters
  src/Magpie/PageFrame.h
  src/Magpie/ProfilePage.cpp
  src/Magpie/ProfilePage.h
  src/Magpie/ProfilePage.xaml
  src/Magpie/Resources.language-en-US.resw
  src/Magpie/Resources.language-zh-Hans.resw
  src/Magpie/RootPage.cpp
  src/Magpie/RootPage.h
  src/Magpie/RootPage.xaml
  src/Magpie/ScalingModesPage.cpp
  src/Magpie/ScalingModesPage.h
  src/Magpie/ScalingModesPage.xaml
  src/Magpie/SettingsCard.h
  src/Magpie/SettingsExpander.h
  src/Magpie/SettingsExpanderCornerRadiusConverter.h
  src/Magpie/SettingsGroup.h
  src/Magpie/SettingsPage.cpp
  src/Magpie/SettingsPage.h
  src/Magpie/ShortcutControl.h
  src/Magpie/SimpleStackPanel.h
  src/Magpie/TextBlockHelper.cpp
  src/Magpie/TextBlockHelper.h
  src/Magpie/TextMenuFlyout.cpp
  src/Magpie/TextMenuFlyout.h
  src/Magpie/TextMenuFlyout.idl
  src/Magpie/TitlebarControl.h
  src/Magpie/WrapPanel.h
  src/Magpie/pch.h
Labels: bug, area: UI

#1153 扩展新建配置弹窗中名称文本框右键菜单功能
  src/Magpie/Resources.language-en-US.resw
  src/Magpie/Resources.language-zh-Hans.resw
  src/Magpie/RootPage.cpp
  src/Magpie/RootPage.h
  src/Magpie/RootPage.xaml
Labels: enhancement

#1156 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ja.resw
  src/Magpie/Resources.language-ko.resw
  src/Magpie/Resources.language-pl.resw
Labels: area: localization

#1155 修复删除缩放模式时崩溃
  src/Magpie/EffectParametersViewModel.cpp
  src/Magpie/EffectParametersViewModel.h
  src/Magpie/ScalingModeEffectItem.cpp
  src/Magpie/ScalingModeEffectItem.h
  src/Magpie/ScalingModeItem.cpp
  src/Magpie/ScalingModeItem.h
Labels: bug, area: UI

#1162 修复选择快捷方式作为启动器时丢失参数
  src/Magpie/AppSettings.cpp
  src/Magpie/FileDialogHelper.cpp
  src/Magpie/Profile.h
  src/Magpie/ProfileViewModel.cpp
Labels: bug
