Repository Blinue/Magpie, pull requests merged in 2025-03, with the labels that each got.

#1096 修复主窗口调整大小时边缘闪烁
  src/Magpie/Magpie.vcxproj
  src/Magpie/Magpie.vcxproj.filters
  src/Magpie/MainWindow.cpp
  src/Magpie/MainWindow.h
  src/Magpie/RootPage.cpp
  src/Magpie/SmoothResizeHelper.cpp
  src/Magpie/SmoothResizeHelper.h
  src/Magpie/TitlebarControl.cpp
  src/Magpie/TitlebarControl.h
  src/Magpie/TitlebarControl.xaml
  src/Magpie/XamlWindow.h
Labels: bug, area: UI

#1103 Translations update from Hosted Weblate
  src/Magpie/Resources.language-id.resw
  src/Magpie/Resources.language-ka.resw
  src/Magpie/Resources.language-zh-Hant.resw
Labels: area: localization

#1102 Detailed performance tips for 24H2 and Nvidia users
  docs/Performance optimization.md
  docs/性能优化建议.md
Labels: area: performance, area: docs
