Repository Blinue/Magpie, pull requests merged in 2025-07, with the labels that each got.

#1183 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ja.resw
Labels: area: localization

#1199 工具栏优化
  src/Magpie.Core/ImGuiFontsCacheManager.cpp
  src/Magpie.Core/Magpie.Core.vcxproj
  src/Magpie.Core/Magpie.Core.vcxproj.filters
  src/Magpie.Core/OverlayDrawer.cpp
  src/Magpie.Core/OverlayHelper.h
  src/Magpie.Core/Renderer.cpp
  src/Magpie.Core/Renderer.h
  src/Magpie.Core/ScalingOptions.cpp
  src/Magpie.Core/ScalingRuntime.cpp
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
  src/Magpie.Core/SrcTracker.cpp
  src/Magpie.Core/SrcTracker.h
  src/Magpie.Core/include/ScalingError.h
  src/Magpie.Core/include/ScalingOptions.h
  src/Magpie.Core/include/ScalingRuntime.h
  src/Magpie/HomeViewModel.cpp
  src/Magpie/HomeViewModel.h
  src/Magpie/Resources.language-en-US.resw
  src/Magpie/Resources.language-ja.resw
  src/Magpie/Resources.language-ru.resw
  src/Magpie/Resources.language-zh-Hans.resw
  src/Magpie/ScalingService.cpp
  src/Magpie/ScalingService.h
Labels: enhancement, area: UI

#1209 不再支持导入 ScaleModels.json
  src/Magpie/AboutPage.cpp
  src/Magpie/AboutPage.h
  src/Magpie/AboutPage.xaml
  src/Magpie/FileDialogHelper.cpp
  src/Magpie/HomePage.cpp
  src/Magpie/HomePage.h
  src/Magpie/HomePage.xaml
  src/Magpie/Resources.language-de.resw
  src/Magpie/Resources.language-en-US.resw
  src/Magpie/Resources.language-es.resw
  src/Magpie/Resources.language-fr.resw
  src/Magpie/Resources.language-id.resw
  src/Magpie/Resources.language-it.resw
  src/Magpie/Resources.language-ja.resw
  src/Magpie/Resources.language-ka.resw
  src/Magpie/Resources.language-ko.resw
  src/Magpie/Resources.language-pl.resw
  src/Magpie/Resources.language-pt-BR.resw
  src/Magpie/Resources.language-ru.resw
  src/Magpie/Resources.language-ta.resw
  src/Magpie/Resources.language-tr.resw
  src/Magpie/Resources.language-uk.resw
  src/Magpie/Resources.language-vi.resw
  src/Magpie/Resources.language-zh-Hans.resw
  src/Magpie/Resources.language-zh-Hant.resw
  src/Magpie/ScalingModesPage.xaml
  src/Magpie/ScalingModesService.cpp
  src/Magpie/ScalingModesService.h
  src/Magpie/ScalingModesViewModel.cpp
  src/Magpie/ScalingModesViewModel.h
  src/Magpie/ScalingModesViewModel.idl
Labels: enhancement

#1214 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ja.resw
Labels: area: localization

#1216 全屏缩放默认不再置顶
  src/Magpie.Core/AdaptivePresenter.h
  src/Magpie.Core/CompSwapchainPresenter.h
  src/Magpie.Core/ScalingOptions.cpp
  src/Magpie.Core/ScalingRuntime.cpp
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
  src/Magpie.Core/SrcTracker.cpp
  src/Magpie.Core/include/ScalingOptions.h
  src/Magpie/AppSettings.cpp
  src/Magpie/AppSettings.h
  src/Magpie/HomePage.xaml
  src/Magpie/HomeViewModel.cpp
  src/Magpie/HomeViewModel.h
  src/Magpie/HomeViewModel.idl
  src/Magpie/MainWindow.h
  src/Magpie/ProfilePage.xaml
  src/Magpie/ProfileViewModel.cpp
  src/Magpie/ProfileViewModel.h
  src/Magpie/ProfileViewModel.idl
  src/Magpie/Resources.language-en-US.resw
  src/Magpie/Resources.language-zh-Hans.resw
  src/Magpie/ScalingService.cpp
  src/Magpie/Shortcut.h
  src/Magpie/ToastPage.cpp
Labels: enhancement

#1218 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ja.resw
Labels: area: localization
