Repository Blinue/Magpie, pull requests merged in 2025-08, with the labels that each got.

#1223 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ja.resw
Labels: area: localization

#1227 优化自动缩放机制
  Magpie.sln
  src/Magpie.Core/AdaptivePresenter.cpp
  src/Magpie.Core/OverlayDrawer.cpp
  src/Magpie.Core/ScalingRuntime.cpp
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/ScalingWindow.h
  src/Magpie.Core/include/ScalingRuntime.h
  src/Magpie/ScalingService.cpp
  src/Magpie/ScalingService.h
Labels: enhancement

#1234 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ja.resw
Labels: area: localization

#1239 Translations update from Hosted Weblate
  src/Magpie/Resources.language-pl.resw
Labels: area: localization

#1248 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ru.resw
Labels: area: localization

#1252 修复有时误报源窗口无响应
  src/Magpie.Core/SrcTracker.cpp
  src/Magpie.Core/Win32Helper.cpp
  src/Magpie/ToastPage.cpp
  tools/WindowCase/HungWindow.cpp
  tools/WindowCase/HungWindow.h
  tools/WindowCase/KirikiriWindow.cpp
  tools/WindowCase/KirikiriWindow.h
  tools/WindowCase/WindowBase.h
  tools/WindowCase/WindowCase.vcxproj
  tools/WindowCase/WindowCase.vcxproj.filters
  tools/WindowCase/main.cpp
  tools/WindowCase/pch.h
Labels: bug, area: compatibility

#1255 自绘非客户区的窗口不再保留非客户区
  src/Magpie.Core/ScalingWindow.cpp
  src/Magpie.Core/SrcTracker.cpp
  src/Magpie.Core/SrcTracker.h
Labels: bug, area: compatibility

#1280 Translations update from Hosted Weblate
  src/Magpie/Resources.language-ru.resw
Labels: area: localization
